---
title: "Plotly"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(plotly)
library(flexdashboard)
library(p8105.datasets)
```


```{r load_clean_data, echo = FALSE}
ny_noaa_data = 
  ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, c("year", "month", "day"), sep = "-") %>% 
  mutate(tmin = as.numeric(tmin) / 10,
         tmax = as.numeric(tmax) / 10,
         prcp = prcp / 10,
         month = month.name[as.integer(month)],
         year = as.numeric(year))
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Average Maximum Temperature (°C) of New York in January and July from 1981-2010

```{r avg_max_temp, warning = FALSE}
ny_noaa_data %>% 
  filter(month %in% c("January", "July")) %>% 
  group_by(year, month) %>% 
  summarize(avg_max_temp = mean(tmax, na.rm = TRUE)) %>% 
  plot_ly(x = ~year, y = ~avg_max_temp, type = "scatter", mode = "markers", color = ~month) %>%
  layout(
      xaxis = list(title = "Year"),
      yaxis = list(title = "Average maximum temperature (°C)"))
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Average Precipitation (mm) in New York from 1981-2010

```{r avg_prcp}

```

### Chart C: Average Snow Fall (mm) in New York in November - March of 1981 vs. 2010

```{r avg_snow}
ny_noaa_data %>% 
  filter(month %in% c("November", "December", "January", "February", "March"), year %in% c("1981", "2010")) %>% 
  group_by(year, month) %>% 
  summarize(avg_snow = mean(snow, na.rm = TRUE)) %>% 
  mutate(month = fct_reorder(month, avg_snow)) %>% 
  plot_ly(y = ~avg_snow, color = ~month, type = "bar", colors = "Set2") %>%
  layout(
      xaxis = list(title = "Year"),
      yaxis = list(title = "Average snow fall (mm)"))
```